### ISSUE TITLE
IDA versions < 6.9

### ISSUE THREAD

**Issue by kevinhartman** [alexhude/uEmu#13]
IDA changed from PySide to PyQt in [6.9](https://www.hex-rays.com/products/ida/6.9/index.shtml). Perhaps it's worth adding a min version to the readme (or support for PySide 😄).

**Comment by kevinhartman** [comment]
This at least appears to be sufficient, though I haven't been able to test much other than starting up the emulator and providing some CPU context values.

I don't have time to add support for this cleanly in a PR, but perhaps someone else will find it useful, or can incorporate this.

https://gist.github.com/kevinhartman/e3d96cbcb8472d4f69abfe14f5fdca56

**Comment by alexhude** [comment]
Thanks for your comment, I will mention minimum version (6.95) in the next update.
