### ISSUE TITLE
Feature suggestion: appcalls

### ISSUE THREAD

**Issue by Jinmo** [alexhude/uEmu#2]
How about extending this emulation capability to IDAPython console? Like:

```python
print hex(Appcall['some_hash']('hey!!'))
>> 0x12345678
```

It would be pretty cool

**Comment by alexhude** [comment]
There are no plans to implement something like that because:
1. implementation seriously depends on current ABI
2. memory for custom input parameters needs to be allocated somewhere within the context
3. this can be easily achieved via CPU context update before call and breakpoint after call

**Comment by Jinmo** [comment]
Thank you for the reply, I agree with everything. For ABI problem, I'm gonna open issue if a sexy way comes to my mind. (Like, `Appcall[0x1000](r0=0, r1=1, ...).r0 == <return_value>`)
