### ISSUE TITLE
Nice plugin but not useful

### ISSUE THREAD

**Issue by maskelihileci** [alexhude/uEmu#29]
Some features are needed

1. Automatic eip tracking
2. Instruction tracing and Function tracing 
3. Trace windows
4. Trace color
5.General registers list

**Comment by maskelihileci** [comment]
Friend, why are you hiding some features: D

        self.MENU_ITEMS.append(UEMU_HELPERS.MenuItem(self.plugin_name + ":settings",          self.show_settings,         "Settings",                   "Settings",                  None,                   False   ))

**Comment by alexhude** [comment]
Sorry for late reply.
Thank you for your opinion.

Settings are available through IDA menu and not hidden.

I believe some features you request are pretty specific while my goal is to keep uEmu very minimalistic. Therefore I suggest you to implement eEmu extension for that using API: https://github.com/alexhude/uEmu/tree/master/Extensions

Thank you.

**Comment by maskelihileci** [comment]
I use this plugin to simulate virtualization
The only missing thing I feel right now is not seeing the register values here.

[uEmu]: * TRACE <I> 0x1077565 | 33 D9 | xor ebx, ecx
[uEmu]: * TRACE <I> 0x1077567 | 80 DE 2E | sbb dh, 2Eh; '.'
[uEmu]: * TRACE <I> 0x107756A | 3B D0 | cmp edx, eax
[uEmu]: * TRACE <I> 0x107756C | 81 EE 04 00 00 00 | sub esi, 4
[uEmu]: * TRACE <I> 0x1077572 | 0F AB CA | bts edx, ecx
[uEmu]: * TRACE <I> 0x1077575 | D2 C2 | role dl, cl
[uEmu]: * TRACE <I> 0x1077577 | 0F BD D1 | bsr edx, ecx
[uEmu]: * TRACE <I> 0x107757A | 89 0E | mov [es], ecx
[uEmu]: * TRACE <I> 0x107757C | 81 C2 00 69 F2 73 | add edx, 73F26900h
[uEmu]: * TRACE <I> 0x1077582 | 8D AD FC FF FF FF | lea ebp, [ebp-4]
