### ISSUE TITLE
problem with using uEmu in ida 7.6

### ISSUE THREAD

**Issue by ghost** [alexhude/uEmu#30]
![image](https://user-images.githubusercontent.com/77312921/128226401-d6a311d0-4d82-48cb-93d4-14d638adcdb6.png)
How can I fix this?

I have the path 
`C:\Users\lolxd\Downloads\Ida 7.6\python\3\PyQt5\python_3.9`
Specified in the PATH system variable.

**Comment by ThiagoAlexsander** [comment]
pip install PyQt5

**Comment by alexhude** [comment]
Thanks @ThiagoAlexsander!
I don't have windows IDA to check, but this solution sounds right.
