### ISSUE TITLE
IDA PRO 7.6 Pull request

### ISSUE THREAD

**Issue by maskelihileci** [alexhude/uEmu#32]
I couldn't create pull request on the other side so I request code fix here.

![image](https://user-images.githubusercontent.com/41159853/141648301-7f3e758b-afac-4e86-a4ef-68c1848d4691.png)

![image](https://user-images.githubusercontent.com/41159853/141648328-727fec12-3ec9-444b-84e1-0b0bf1f335d8.png)

This fixes the convert to code automatically error for 7.6.

https://hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

**Comment by alexhude** [comment]
Thanks for your PR. Fixed in e183068.
