### ISSUE TITLE
reset error

### ISSUE THREAD

**Issue by anylayer** [alexhude/uEmu#33]
win10
ida7.6
python3.9.6

Ida crashes when click rest in uEmu.
After restarting IDA, I  found that the IDA data file was occupied.
Try again many times and the same will happen again.

![image](https://user-images.githubusercontent.com/46556817/163088280-4ac1749a-3485-4f53-92b9-2fcfb1f78b56.png)

**Comment by anylayer** [comment]
![image](https://user-images.githubusercontent.com/46556817/163088526-966364f4-a5d7-4450-8b94-b61f9e32d0a0.png)

**Comment by alexhude** [comment]
Thank you for report, I tried it on IDA 8.0 (macOS) with ARM32 and ARM64 binaries. Unable to reproduce.
