### ISSUE TITLE
ARM emulator does not support thumb mode

### ISSUE THREAD

**Issue by wbokslag** [alexhude/uEmu#6]
Hi,

Thanks for your great plugin, it's very useful. However, it does not properly emulate ARM in thumb mode. In order to fix this, the following line should be added to the start of step_thread_main()

```
if get_arch()[0:3] == "arm" and GetReg(self.pc, "T"):
    self.pc |= 1
```

Possibly, it would be a good idea to store get_arch() in a class variable, as it is now frequently computed while it is a constant value. This negatively impacts emulation speed. 

Kind regards,

Wouter

**Comment by alexhude** [comment]
Yep, I know, and it is not that simple, there are some corner cases. I am working on update.
