### ISSUE TITLE
load warning: no modular ida_hexrays

### ISSUE THREAD

**Issue by echowwww** [alexhude/uEmu#8]
Hi, 
when I load the plugin in IDA Pro, it alerts that there is no modular named ida_hexrays, ida_kernwin and ida_allins. uEmu.py locates in ida's /plugins directory.
Would you please give me a clue how to fix this problem? thanks.

**Comment by alexhude** [comment]
As soon as you set `UEMU_USE_AS_SCRIPT = False` and put it into `IDA/plugins` folder, it should load just fine.
```
[uEmu]: Init plugin
[uEmu]: UI ready. Run plugin
[uEmu]: CPU arch set to [ arm64le ]
```
I have tested it with IDA 6.9.5 and IDA 7.1
